# compose 파일 버전
version: '3'
services:
  # 서비스 명
  db:
    # Build info
    build:
      context: docker/sangdo_postgis
    # 컨테이너 실행 시 재시작
    restart: on-failure
    # 컨테이너명 설정
    container_name: sangdo_postgis
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - '5432:5432'
    # 환경 변수 설정
    environment:
      # PostgreSQL 계정 및 패스워드 설정 옵션
      POSTGRES_USER: api_test
      POSTGRES_PASSWORD: sangdojoong
    # 볼륨 설정
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    networks:
      - backend

  fastapi:
    # Build info
    build:
      context: .
      dockerfile: docker/sangdo_api_server/Dockerfile
      # 컨테이너 실행 시 재시작
    restart: on-failure
    # 컨테이너명 설정
    container_name: sangdo_api_server
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - '8080:8080'
    environment:
      - APP_ENV=dev
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./app:/app/app
      - /home/ubuntu/uploads:/uploads
    networks:
      - backend

networks:
  backend:
    driver: bridge
